service: diogenes-pro

provider:
  name: aws
  runtime: nodejs8.10

package:
  include:
    - handler.js
  exclude:
    - "**/*"

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
